class World {
  final int id;
  final String title, subtitle, emoji;
  final List<Mission> missions;
  const World(this.id, this.title, this.subtitle, this.emoji, this.missions);
}

class Mission {
  final int id;
  final String title, subtitle, emoji, story, reward;
  final List<String> words;
  const Mission(this.id, this.title, this.subtitle, this.emoji, this.story,
      this.reward, this.words);
}

const worlds = [
  World(1, 'Fox Village', 'Where the adventure begins', '🏡', const [
    Mission(
        1,
        'The Missing Words',
        'Find the first lost words',
        '📖',
        'The magic Word Book is empty! Fox needs your help to find the first words.',
        'Fox Explorer Badge',
        ['cat', 'dog', 'bird', 'fish', 'fox']),
    Mission(
        2,
        'Animal Friends',
        'Meet the village animals',
        '🐾',
        'Fox wants to introduce you to his animal friends. Can you find them?',
        'Animal Friend Badge',
        ['cat', 'dog', 'bird', 'fish', 'rabbit', 'bear']),
    Mission(
        3,
        'The Lost Colors',
        'Bring the colors back',
        '🌈',
        'Oh no! The colors have disappeared from Fox Village. Let’s bring them back!',
        'Rainbow Ribbon',
        ['red', 'blue', 'yellow', 'green', 'pink', 'orange']),
    Mission(4, "Fox's Birthday", 'Count the presents', '🎂',
        'It is Fox’s birthday! Help him count the presents.', 'Birthday Hat', [
      'one',
      'two',
      'three',
      'four',
      'five',
      'six',
      'seven',
      'eight',
      'nine',
      'ten'
    ]),
    Mission(
        5,
        'Picnic Time!',
        'Prepare a tasty picnic',
        '🍎',
        'Fox is hungry. Let’s pack the picnic basket together!',
        'Picnic Basket',
        ['apple', 'banana', 'cake', 'milk', 'juice', 'bread']),
    Mission(
        6,
        'Where Is Fox?',
        'Find Fox in the village',
        '🏡',
        'Fox is playing hide-and-seek. Listen carefully and find where he is!',
        'Tiny Backpack',
        ['in', 'on', 'under', 'next to']),
    Mission(
        7,
        'The Word Book',
        'Save Fox Village',
        '✨',
        'The final pages of the Word Book are waiting. Show what you have learned!',
        'Fox Village Hero Crown',
        ['dog', 'red', 'three', 'apple', 'under', 'fox']),
  ]),
  World(2, 'Animal Forest', 'A mysterious forest full of friends', '🌲', const [
    Mission(
        8,
        'Into the Forest',
        'Meet the forest animals',
        '🌲',
        'A new path is glowing beyond Fox Village. Fox needs a brave explorer!',
        'Forest Explorer Badge',
        ['lion', 'tiger', 'monkey', 'elephant', 'zebra', 'giraffe']),
    Mission(
        9,
        'Who Am I?',
        'Match animals and clues',
        '🦁',
        'The animals are hiding. Listen to Fox’s clues and find the right friend.',
        'Animal Detective Badge',
        ['lion', 'tiger', 'monkey', 'elephant', 'zebra', 'giraffe']),
    Mission(
        10,
        'Big or Small?',
        'Learn animal sizes',
        '🐘',
        'Some forest friends are big, and some are small. Can you sort them?',
        'Forest Compass',
        ['big', 'small', 'long', 'short']),
    Mission(
        11,
        'Fast Forest!',
        'Learn action words',
        '🐒',
        'The forest animals are having a race. Choose what each animal can do!',
        'Speedy Fox Shoes',
        ['run', 'jump', 'swim', 'fly', 'climb', 'walk']),
    Mission(
        12,
        'Animal Homes',
        'Where do they live?',
        '🏠',
        'The sun is setting. Help each animal find its home.',
        'Cozy Forest Tent',
        ['tree', 'river', 'nest', 'cave', 'pond', 'grass']),
    Mission(
        13,
        'Forest Picnic',
        'Choose the food',
        '🍓',
        'The forest friends are hungry. Pack the right food for everyone!',
        'Berry Basket',
        ['apple', 'banana', 'carrot', 'fish', 'bread', 'water']),
    Mission(
        14,
        'The Forest Guardian',
        'Complete the forest quest',
        '🗝️',
        'The Forest Guardian has one final challenge. Show everything you learned!',
        'Forest Hero Cape',
        ['lion', 'green', 'jump', 'tree', 'fish', 'small']),
  ]),
  World(3, 'Rainbow Valley', 'A colorful new adventure', '🌈', [
    Mission(
        15,
        'The Rainbow Gate',
        'Meet the magic colors',
        '🌈',
        'A giant rainbow gate is glowing! Fox needs your help to bring its colors back.',
        'Rainbow Explorer Badge',
        ['red', 'blue', 'yellow', 'green', 'pink', 'purple']),
    Mission(
        16,
        'Sunny Day',
        'Explore the sky',
        '☀️',
        'The sun is shining over the valley. Let’s discover the sky and weather words!',
        'Sunshine Star',
        ['sun', 'cloud', 'sky', 'rain', 'wind', 'rainbow']),
    Mission(
        17,
        'Butterfly Garden',
        'Meet tiny friends',
        '🦋',
        'A secret garden is full of flowers and tiny flying friends. Can you find them?',
        'Garden Friend',
        ['butterfly', 'flower', 'tree', 'grass', 'bee', 'bird']),
    Mission(
        18,
        'Shape Hill',
        'Climb the shape hill',
        '🔷',
        'Fox found a hill covered in magical shapes. Let’s name them together!',
        'Shape Master',
        ['circle', 'square', 'triangle', 'star', 'heart']),
    Mission(
        19,
        'Rainy Adventure',
        'Get ready for rain',
        '☔',
        'Oh no! Rain is coming. Fox needs the right things for a rainy adventure.',
        'Rainy Ranger',
        ['rain', 'umbrella', 'boots', 'coat', 'wet', 'dry']),
    Mission(
        20,
        'The Magic Colors',
        'Mix the colors',
        '🎨',
        'The color crystals have a secret: two colors can make a new color!',
        'Color Wizard',
        ['red', 'yellow', 'orange', 'blue', 'green', 'purple']),
    Mission(
        21,
        'Rainbow Castle',
        'The final challenge',
        '🏰',
        'You reached the Rainbow Castle! Use everything you learned to restore the rainbow.',
        'Rainbow Hero Crown', [
      'red',
      'blue',
      'yellow',
      'green',
      'pink',
      'purple',
      'sun',
      'cloud',
      'butterfly',
      'flower',
      'circle',
      'star',
      'rain',
      'umbrella'
    ]),
  ]),
  World(4, 'Fox Home Town', 'Everyday English adventure', '🏠', [
    Mission(
        22,
        'Welcome Home',
        'Explore the house',
        '🏡',
        'Fox is back home! Let’s explore the rooms and things around the house.',
        'Home Explorer Badge',
        ['house', 'door', 'window', 'room', 'bed', 'kitchen']),
    Mission(
        23,
        'Get Dressed!',
        'Choose the right clothes',
        '👕',
        'Fox is getting ready for a new day. Can you help choose the clothes?',
        'Fashion Fox Badge',
        ['shirt', 'pants', 'dress', 'shoes', 'hat', 'jacket']),
    Mission(
        24,
        'Breakfast Time',
        'Start the day',
        '🍳',
        'Breakfast is ready! Let’s learn the words for Fox’s favorite foods and drinks.',
        'Breakfast Star',
        ['bread', 'milk', 'egg', 'apple', 'cheese', 'juice']),
    Mission(
        25,
        "Fox's Room",
        'Find the room objects',
        '🛋️',
        'Fox’s room is a little messy. Can you find everything he needs?',
        'Room Ranger Badge',
        ['table', 'chair', 'bed', 'lamp', 'book', 'toy']),
    Mission(
        26,
        'Around Town',
        'Travel through town',
        '🚌',
        'Let’s go outside! Fox wants to visit his favorite places around town.',
        'Town Traveler Badge',
        ['bus', 'car', 'bike', 'road', 'park', 'shop']),
    Mission(
        27,
        'The Busy Town',
        'Discover town places',
        '🏪',
        'The town is busy today. Fox needs your help finding the right places.',
        'Town Helper Badge',
        ['school', 'hospital', 'supermarket', 'cafe', 'library', 'playground']),
    Mission(
        28,
        'Town Festival',
        'The big celebration',
        '🎡',
        'It’s festival day! Use everything you learned to help Fox prepare the town party.',
        'Festival Hero Crown', [
      'house',
      'shirt',
      'milk',
      'book',
      'bus',
      'park',
      'school',
      'library',
      'playground'
    ]),
  ]),
  World(5, 'Food Island', 'A delicious English adventure', '🍕', [
    Mission(
        29,
        'Welcome to Food Island',
        'Meet the food friends',
        '🏝️',
        'Fox has arrived on Food Island! Let’s meet some tasty new friends.',
        'Food Explorer Badge',
        ['pizza', 'burger', 'banana', 'orange', 'cake', 'ice cream']),
    Mission(
        30,
        'Fruit Market',
        'Choose fresh fruit',
        '🍎',
        'The fruit market is full of colors and delicious surprises. Can you help Fox?',
        'Fruit Collector Badge',
        ['apple', 'banana', 'orange', 'pear', 'grape', 'watermelon']),
    Mission(
        31,
        'Yummy Breakfast',
        'Build a breakfast',
        '🥞',
        'It is breakfast time! Let’s choose the right food and drinks for Fox.',
        'Breakfast Chef Badge',
        ['bread', 'egg', 'cheese', 'milk', 'juice', 'cereal']),
    Mission(
        32,
        'Fox’s Pizza Shop',
        'Make a pizza',
        '🍕',
        'Fox is making a pizza. Pick the ingredients he needs!',
        'Pizza Master Badge',
        ['pizza', 'tomato', 'cheese', 'ham', 'mushroom', 'pepper']),
    Mission(
        33,
        'Sweet Café',
        'Visit the café',
        '🧁',
        'Welcome to the café! Let’s learn sweet treats and simple café words.',
        'Café Star Badge',
        ['cake', 'cookie', 'ice cream', 'chocolate', 'tea', 'water']),
    Mission(
        34,
        'Food Adventure',
        'Taste and choose',
        '🍽️',
        'The island chefs need help. Choose the food Fox asks for!',
        'Super Taster Badge',
        ['rice', 'chicken', 'fish', 'soup', 'salad', 'sandwich']),
    Mission(
        35,
        'The Great Food Festival',
        'Celebrate with Fox',
        '🎉',
        'It is the Great Food Festival! Use everything you learned to help Fox prepare the feast.',
        'Golden Chef Crown', [
      'pizza',
      'apple',
      'banana',
      'milk',
      'bread',
      'cheese',
      'cake',
      'juice',
      'fish',
      'salad',
      'ice cream'
    ]),
  ]),
  World(6, 'Space World', 'A cosmic English adventure', '🚀', [
    Mission(
        36,
        'Rocket Launch',
        'Get ready for space',
        '🚀',
        'Fox is ready to fly! Let’s learn the words for a rocket launch.',
        'Rocket Ranger Badge',
        ['rocket', 'space', 'star', 'moon', 'sun', 'sky']),
    Mission(
        37,
        'Star Station',
        'Explore the stars',
        '⭐',
        'Welcome to Star Station! Can you find the things Fox sees in space?',
        'Star Explorer Badge',
        ['star', 'planet', 'moon', 'sky', 'light', 'night']),
    Mission(
        38,
        'Planet Adventure',
        'Meet the planets',
        '🪐',
        'Fox is exploring a colorful planet. Let’s discover new space words!',
        'Planet Explorer Badge',
        ['planet', 'Earth', 'Mars', 'ring', 'rock', 'space']),
    Mission(
        39,
        'Alien Friends',
        'Meet a new friend',
        '👽',
        'Someone is waving from a tiny spaceship! Let’s help Fox meet a new alien friend.',
        'Alien Friend Badge',
        ['alien', 'friend', 'robot', 'ship', 'hello', 'help']),
    Mission(
        40,
        'Space Station',
        'Life in space',
        '🛰️',
        'Fox has reached the space station. What can he find inside?',
        'Space Captain Badge',
        ['station', 'door', 'window', 'computer', 'bed', 'food']),
    Mission(
        41,
        'Moon Mission',
        'Explore the moon',
        '🌕',
        'The moon is waiting! Help Fox complete his little moon adventure.',
        'Moon Walker Badge',
        ['moon', 'crater', 'rock', 'flag', 'boots', 'jump']),
    Mission(
        42,
        'The Galaxy Festival',
        'The final space adventure',
        '🌌',
        'The Galaxy Festival is starting! Use everything you learned to help Fox celebrate among the stars.',
        'Galaxy Hero Crown', [
      'rocket',
      'star',
      'planet',
      'moon',
      'alien',
      'robot',
      'Earth',
      'Mars',
      'space',
      'flag',
      'friend'
    ]),
  ]),
];

final List<Mission> allMissions =
    worlds.expand((w) => w.missions).toList(growable: false);
